### PR TITLE
XIVY-12479 run tests against openvscode-server

### PR DESCRIPTION
**Pull request by ivy-lmu**
- chromium is used for testing
- new pipe https://jenkins.ivyteam.io/job/vscode-extensions_integration-openvscode-server/

tests will be stabilized in a followup

### CODE REVIEW

**Review by ivy-lli — APPROVED** [review]
😎

**Review by alexsuter — APPROVED** [review]

**Review by ivy-cst — COMMENTED** [review]
:tada:

**Comment by ivy-lli** [comment]
Didn't you want to squash your commits together before merging them? 🤣

**Comment by ivy-lmu** [comment]
I did so, https://github.com/axonivy/vscode-extensions/commits/master, or what do you mean?

**Comment by ivy-lli** [comment]
ah squash + merge?

**Comment by ivy-lmu** [comment]
> ah squash + merge?
yes 😽

**Pull request merged**
